### ISSUE TITLE
IObjects are not valid as a React child (found: Error: Network error: Failed to fetch).

### ISSUE THREAD

**Issue by drimpact** [impactasaurus/app#433]
https://sentry.io/impactasaurus/web-app/issues/836178743/?referrer=github_plugin

```
Invariant Violation: Objects are not valid as a React child (found: Error: Network error: Failed to fetch).
  at aa (./node_modules/fbjs/lib/invariant.js:42:1)
  at A (./node_modules/react-dom/cjs/react-dom.production.min.js:14:166)
  at wg (./node_modules/react-dom/cjs/react-dom.production.min.js:154:18)
  at yg (./node_modules/react-dom/cjs/react-dom.production.min.js:164:109)
  at Jg (./node_modules/react-dom/cjs/react-dom.production.min.js:166:383)
...
(12 additional frame(s) were not displayed)
```

**Comment by drimpact** [comment]
This will be because of using Error objects directly in the DOM. https://github.com/impactasaurus/app/issues/681 is clearing this up.
