### ISSUE TITLE
Meeting with empty questionnaire fails

### ISSUE THREAD

**Issue by drimpact** [impactasaurus/app#496]
https://sentry.io/organizations/impactasaurus/issues/1466677006/?referrer=github_plugin

```
TypeError: Cannot read property 'id' of undefined
  at setMeetingState (./src/app/containers/Meeting/index.tsx:131:33)
  at componentDidUpdate (./src/app/containers/Meeting/index.tsx:80:12)
  at Array.forEach (<anonymous>)
  at Array.forEach (<anonymous>)
  at Array.forEach (<anonymous>)
...
(17 additional frame(s) were not displayed)
```

**Comment by drimpact** [comment]
This occurred when continuing an incomplete record which belonged to a questionnaire with no questions. I believe creating a record to a questionnaire without questions is not possible, but continuing obviously is allowed.
