### ISSUE TITLE
Cannot read property 'toFixed' of undefined

### ISSUE THREAD

**Issue by drimpact** [impactasaurus/app#79]
Got the following stack trace on `https://app.impactasaurus.org/settings/questions/f120a00e-82fc-4ff4-a817-af6fd60baf47`

```
TypeError: Cannot read property 'toFixed' of undefined
  at Object.f [as b](./node_modules/rc-slider/es/utils.js:76:1)
  at trimAlignValue(./node_modules/rc-slider/es/Slider.js:118:1)
  at componentWillReceiveProps(./node_modules/rc-slider/es/Slider.js:49:1)
  at updateComponent(./node_modules/react-dom/lib/ReactCompositeComponent.js:613:1)
  at receiveComponent(./node_modules/react-dom/lib/ReactCompositeComponent.js:546:1)
  at receiveComponent(./node_modules/react-dom/lib/ReactReconciler.js:124:1)
  at _updateRenderedComponent(./node_modules/react-dom/lib/ReactCompositeComponent.js:753:1)
  at _performComponentUpdate(./node_modules/react-dom/lib/ReactCompositeComponent.js:723:1)
  at updateComponent(./node_modules/react-dom/lib/ReactCompositeComponent.js:644:1)
  at receiveComponent(./node_modules/react-dom/lib/ReactCompositeComponent.js:546:1)
  at receiveComponent(./node_modules/react-dom/lib/ReactReconciler.js:124:1)
  at updateChildren(./node_modules/react-dom/lib/ReactChildReconciler.js:109:1)
  at _reconcilerUpdateChildren(./node_modules/react-dom/lib/ReactMultiChild.js:211:1)
  at _updateChildren(./node_modules/react-dom/lib/ReactMultiChild.js:310:1)
  at updateChildren(./node_modules/react-dom/lib/ReactMultiChild.js:297:1)
  at _updateDOMChildren(./node_modules/react-dom/lib/ReactDOMComponent.js:942:1)
  at updateComponent(./node_modules/react-dom/lib/ReactDOMComponent.js:760:1)
  at receiveComponent(./node_modules/react-dom/lib/ReactDOMComponent.js:722:1)
  at receiveComponent(./node_modules/react-dom/lib/ReactReconciler.js:124:1)
  at updateChildren(./node_modules/react-dom/lib/ReactChildReconciler.js:109:1)
  at _reconcilerUpdateChildren(./node_modules/react-dom/lib/ReactMultiChild.js:211:1)
  at _updateChildren(./node_modules/react-dom/lib/ReactMultiChild.js:310:1)
  at updateChildren(./node_modules/react-dom/lib/ReactMultiChild.js:297:1)
  at _updateDOMChildren(./node_modules/react-dom/lib/ReactDOMComponent.js:942:1)
  at updateComponent(./node_modules/react-dom/lib/ReactDOMComponent.js:760:1)
  at receiveComponent(./node_modules/react-dom/lib/ReactDOMComponent.js:722:1)
  at receiveComponent(./node_modules/react-dom/lib/ReactReconciler.js:124:1)
  at updateChildren(./node_modules/react-dom/lib/ReactChildReconciler.js:109:1)
  at _reconcilerUpdateChildren(./node_modules/react-dom/lib/ReactMultiChild.js:211:1)
  at _updateChildren(./node_modules/react-dom/lib/ReactMultiChild.js:310:1)
  at updateChildren(./node_modules/react-dom/lib/ReactMultiChild.js:297:1)
  at _updateDOMChildren(./node_modules/react-dom/lib/ReactDOMComponent.js:942:1)
  at updateComponent(./node_modules/react-dom/lib/ReactDOMComponent.js:760:1)
  at receiveComponent(./node_modules/react-dom/lib/ReactDOMComponent.js:722:1)
  at receiveComponent(./node_modules/react-dom/lib/ReactReconciler.js:124:1)
  at _updateRenderedComponent(./node_modules/react-dom/lib/ReactCompositeComponent.js:753:1)
  at _performComponentUpdate(./node_modules/react-dom/lib/ReactCompositeComponent.js:723:1)
  at updateComponent(./node_modules/react-dom/lib/ReactCompositeComponent.js:644:1)
  at receiveComponent(./node_modules/react-dom/lib/ReactCompositeComponent.js:546:1)
  at receiveComponent(./node_modules/react-dom/lib/ReactReconciler.js:124:1)
  at updateChildren(./node_modules/react-dom/lib/ReactChildReconciler.js:109:1)
  at _reconcilerUpdateChildren(./node_modules/react-dom/lib/ReactMultiChild.js:211:1)
  at _updateChildren(./node_modules/react-dom/lib/ReactMultiChild.js:310:1)
  at updateChildren(./node_modules/react-dom/lib/ReactMultiChild.js:297:1)
  at _updateDOMChildren(./node_modules/react-dom/lib/ReactDOMComponent.js:942:1)
  at updateComponent(./node_modules/react-dom/lib/ReactDOMComponent.js:760:1)
  at receiveComponent(./node_modules/react-dom/lib/ReactDOMComponent.js:722:1)
  at receiveComponent(./node_modules/react-dom/lib/ReactReconciler.js:124:1)
  at _updateRenderedComponent(./node_modules/react-dom/lib/ReactCompositeComponent.js:753:1)
  at d._performComponentUpdate(./node_modules/react-dom/lib/ReactCompositeComponent.js:723:1)
```

**Comment by wilsonkasey** [comment]
I can help with this issue.

**Comment by nikw92** [comment]
How do I reproduce this issue? Also, I cannot access the sentry log without logging in.
